name: "Nitro Client Upload"
description: "Uploads client operations to the Nitro registry"
author: "ChilliCream"
branding:
  icon: "upload-cloud"
  color: "orange"

inputs:
  tag:
    description: "The tag of the client version"
    required: true
  client-id:
    description: "The ID of the client"
    required: true
  api-key:
    description: "API key for authentication"
    required: true
    secret: true
  operations-file:
    description: "The path to the JSON file with the operations"
    required: true
  cloud-url:
    description: "The URL of the Nitro registry"
    required: false
  job-id:
    description: "The ID of the current job"
    required: false
    default: ${{ job.check_run_id }}

runs:
  using: "node20"
  main: "dist/index.js"
